### ISSUE TITLE
Différences YAML -> JSON (pour import dans le cloud)

### ISSUE THREAD

**Issue by clemzarch** [php-etl/satellite#128]
Il y a des différences entre un YAML valide qui se compile et s'execute, et un JSON qu'execution-domain accepte via l'api.

YAML valide:
```
version: '0.3'
satellites:
  tags:
    label: 'Tags'
    composer:
      repositories:
        - name: prestashop/prestashop-webservice-lib
          type: vcs
          url: 'https://github.com/php-etl/prestashop-webservice-lib.git'
    workflow:
      jobs:
        - pipeline:
            steps:
              - example:
                  foo: bar
```
JSON valide:
```
{
  "code": "tags",          #1
  "label": "Tags",
  "composer": {
    "repositories": [
      {
        "name": "prestashop/prestashop-webservice-lib",
        "type": "vcs",
        "url": "https://github.com/php-etl/prestashop-webservice-lib.git"
      }
    ]
  },
  "jobs": [
    {
      "code": "pipeline1",         #2
      "pipeline": {
        "steps": [
          {
            "code": "step",         #3
            "configuration": {         #4
              "example": {
                "foo": "bar"
              }
            },
            "probes": [
              { "code": "read", "label": "Read" },                ]
              { "code": "rejected", "label": "Rejected" },        ]  #5
              { "code": "errors", "label": "Errors" }             ]
            ]
          }
        ]
      }
    }
  ]
}
```

par rapport au yaml local, un json pour le cloud veut obligatoirement:
- [ ] `code` sur le satellite (`#1`)
- [ ] `code` sur le job/sur la pipeline (`#2`)
- [ ] `code` sur la step (`#3`)
- [ ] encapsulation de la config de la step dans une `configuration` (`#4`)
- [ ] `probes` sur la step (`#5`)
