### ISSUE TITLE
TODO pour faire fonctionner API Runtime

### ISSUE THREAD

**Issue by clemzarch** [php-etl/satellite#36]
todo :

- [ ] Kiboko\Component\Satellite\Console\StateOutput\API -> est-ce qu'il faut implementer les States ?
- [ ]  Kiboko\Component\Satellite\Console\APIConsoleRuntime
- [x] compileApiJob dans src/Service : est-ce qu'il faut les plugins ?

A quoi sert `function:` ?
